# Generated by Django 5.0.1 on 2024-02-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maydon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
